name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Cross-compile ${{ matrix.goos }}-${{ matrix.goarch }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64

    outputs:
      matrix: ${{ toJson(matrix) }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build binary and archive
        run: |
          NAME="lazyhetzner"
          EXT=""
          if [ "${{ matrix.goos }}" = "windows" ]; then EXT=".exe"; fi

          BIN_NAME="${NAME}${EXT}"
          OUTPUT_DIR="${NAME}-${{ matrix.goos }}-${{ matrix.goarch }}"
          mkdir -p "$OUTPUT_DIR"

          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} 
          go build -ldflags "-X main.version=${{ github.ref_name }} -X main.commit=${{ github.sha }} -X main.date=$(date -u +%Y-%m-%dT%H:%M:%SZ)"  -o "$OUTPUT_DIR/$BIN_NAME" .

          cp LICENSE "$OUTPUT_DIR/"
          cp README.md "$OUTPUT_DIR/"

          tar -czvf "${OUTPUT_DIR}.tar.gz" "$OUTPUT_DIR"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.goos }}-${{ matrix.goarch }}
          path: |
            *.tar.gz

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Generate SHA256 checksums
        run: |
          cd dist
          find . -name '*.tar.gz' -exec sha256sum {} \; > SHA256SUMS

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: false
          overwrite: true
          files: |
            dist/**/*.tar.gz
            dist/SHA256SUMS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

